apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: client-credentials-resource-server
    apps.tanzu.vmware.com/workload-type: web
  name: client-credentials-resource-server
  namespace: dev
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  serviceClaims:
  - name: ca-cert
    ref:
      apiVersion: v1 
      kind: Secret
      name: tap-ca 
  source:
    git:
      ref:
        branch: main
      url: https://github.com/x95castle1/client-credentials-appsso