apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: resource-server-client-credentials
    apps.tanzu.vmware.com/workload-type: web
  name: resource-server-client-credentials
  namespace: dev
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  serviceClaims:
  - name: ca-cert
    ref:
      apiVersion: v1 
      kind: Secret
      name: tap-ca 
  - name: appsso-demo-client-registration
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: appsso-demo-client-registration
  source:
    git:
      ref:
        branch: main
      url: https://github.com/x95castle1/client-credentials-appsso-resource-server